### ISSUE TITLE
Many empty documents created

### ISSUE THREAD

**Issue by Morgbn** [socketio/socket.io-mongo-adapter#1]
Hello, firstly, thanks for this adapter!
I'm not sure if this issue is a bug or a misunderstanding on my part.
Why documents without data are stored in the database ?
![image](https://user-images.githubusercontent.com/25689856/157672466-9163e58e-1f52-4c41-a2db-1e56d20fa2d6.png)
what is the purpose ?

**Comment by darrachequesne** [comment]
Hi! These are pings packets sent between the Socket.IO servers, in order to know the number of servers which are currently in the cluster (which is needed [here](https://github.com/socketio/socket.io-mongo-adapter/blob/main/lib/index.ts#L442) and [here](https://github.com/socketio/socket.io-mongo-adapter/blob/cec123a03f8c5d847eeaf5cb52f079b5f372b48a/lib/index.ts#L503)).

**Comment by Morgbn** [comment]
Okay, thanks for the information!
