### ISSUE TITLE
Adapter not supporting binary data

### ISSUE THREAD

**Issue by tmotagam** [socketio/socket.io-mongo-adapter#10]
Hi,
I am trying to send binary data UInt8Array the data is going from client to server properly but when the server broadcast the received data the other server in the cluster is not receiving the data it receives this.
```javascript
{ placeholder: true, num: 0 }
```
when I see the mongodb collection also shows what I receives on the receiving client.
Also the client on the receiving end disconnects once this malformed data starts to come in

socket.io server version: 4.5.4
socket.io client version: 4.5.4
nodejs: 18.0
os: windows
mongodb: 5

**Comment by darrachequesne** [comment]
Hi! I could indeed reproduce with the latest `mongodb` version, I'm digging into this.

**Comment by darrachequesne** [comment]
OK, so I think I have found the culprit, this should be fixed by https://github.com/socketio/socket.io-parser/commit/ae8dd88995dbd7f89c97e5cc15e5b489fa0efece, included in `socket.io-parser@4.2.2`.

I've also added a test here: https://github.com/socketio/socket.io-mongo-adapter/commit/ea20cce49f3590ea93230aae44a747f3ca8fe5a9

Thanks a lot for the clear report :+1:

Please reopen if needed!
