### ISSUE TITLE
Indexing for Performance Improvements

### ISSUE THREAD

**Issue by SebassCoates** [socketio/socket.io-mongo-adapter#8]
Are there any issues with adding indexes to the capped collection? 

Different tenants in our system will have unique nsp values, which seems like it might be a natural index. Just wondering if you've considered this might improve performance, or if it's better to leave out. Thanks!

**Comment by darrachequesne** [comment]
Hi!

Since we are using one single MongoDB change stream for all namespaces (since version [0.2.0](https://github.com/socketio/socket.io-mongo-adapter/releases/tag/0.2.0), see https://github.com/socketio/socket.io-mongo-adapter/commit/9b5f4c83038cc212b898b7fb7ff0ccec3124447c), I don't think adding an index on the `nsp` field is needed.

That being said, the connection state recovery feature added in version [0.3.0](https://github.com/socketio/socket.io-mongo-adapter/releases/tag/0.2.0) could use the following indexes:

https://github.com/socketio/socket.io-mongo-adapter/blob/b39f5d5b32f6a5dd6535a54d4dc9c9da1749b0c8/lib/index.ts#L810
https://github.com/socketio/socket.io-mongo-adapter/blob/b39f5d5b32f6a5dd6535a54d4dc9c9da1749b0c8/lib/index.ts#L830

**Comment by SebassCoates** [comment]
Sorry I didn't see your this until now (not sure how I missed it), but I appreciate the thoughtful response. Sorry for leaving this open for so long but I'll close now.
